format = "[┌](bold green) $all$line_break[│](bold green)$line_break[└](bold green) $character"

[character]
success_symbol = "[λ](bold blue)"
error_symbol = "[ε](bold red)"
vicmd_symbol = "[δ](bold purple)"
